name: Build and Deploy

env: 
  GO_URL: https://github.com/Viasat/Viasat-NetworkTrafficMeter.git

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest
    env:
      GH_TOKEN: ${{ github.token }}

    steps:

    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Install Node.js and npm
      uses: actions/setup-node@v2
      with:
        node-version: 18

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.21.x 

    - name: Clone go project
      run: git clone ${{env.GO_URL}} backend

    - name: Build backend
      run: |
        cd ./backend/go-backend/go
        go build -ldflags -H=windowsgui -o ViasatTrafficCapture.exe .
        cd ../../../
        mv ./backend/go-backend/go/ViasatTrafficCapture.exe .

    - name: Install frontend dependencies
      run: npm install

    - name: Build frontend
      run: npm run build:prod
    
    - name: Compile
      run: mv ./ViasatTrafficCapture.exe ./packages/main/ && npm run compile:win

    - name: Echo
      run: echo ls

    - name: Save UI artifacts
      uses: actions/upload-artifact@v2
      with:
        name: ViasatNetworkMetter
        path: "dist/Viasat Network Traffic Metter.exe"
        
  release:
      runs-on: ubuntu-latest
      needs: [build]
      steps:
      - uses: actions/checkout@master
      
      - name: Download Artifact
        uses: actions/download-artifact@v2
        with:
          name: ViasatNetworkMetter
      
      - name: Create Release
        uses: actions/create-release@v1
        id: create_release
        with:
          draft: false
          prerelease: false
          release_name: Release ${{ github.run_number }}
          tag_name: V${{ github.run_number }}
        env:
          GITHUB_TOKEN: ${{ github.token }}
      
      - name: Upload Windows Artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./Viasat Network Traffic Metter.exe
          asset_name: Viasat Network Traffic Metter.exe
          asset_content_type: application/zip
      
